using System.Collections.Generic;
using System.Reflection;
using RimWorld;
using Verse;

namespace PersonaWeaponsUnbound
{
    /// <summary>
    /// Mutates a weapon Thing in place: adds/removes traits, sets cosmetic
    /// properties (name, color), and spawns refunded resources. Def conversion
    /// (base↔unique) lives in <see cref="WeaponDefConversion"/>; ingredient
    /// gathering and reservation for a customization job lives in
    /// <see cref="HaulPlanning.IngredientReservation"/>.
    /// </summary>
    public static class WeaponModificationUtility
    {
        // Reflection fields for CompUniqueWeapon private members. Resolved once
        // at static-init; verified by Initialize() so a RimWorld API rename
        // surfaces as a startup error instead of a silent no-op on every
        // SetName/SetColor/AddTrait/RemoveTrait at runtime.
        internal static readonly FieldInfo CompNameField = typeof(CompUniqueWeapon)
            .GetField("name", BindingFlags.NonPublic | BindingFlags.Instance);

        internal static readonly FieldInfo CompColorField = typeof(CompUniqueWeapon)
            .GetField("color", BindingFlags.NonPublic | BindingFlags.Instance);

        internal static readonly FieldInfo IgnoreAccuracyField = typeof(CompUniqueWeapon)
            .GetField("ignoreAccuracyMaluses", BindingFlags.NonPublic | BindingFlags.Instance);

        // Verb caches burstShot{Speed,Count}Multiplier-folded results on first
        // access of TicksBetweenBurstShots / BurstShotCount and never
        // invalidates them. The fields aren't Scribed, so reloading the save
        // resets them to null and the next access recomputes — which is why
        // burst-trait stat changes don't take effect until reload. Cleared
        // alongside the IgnoreAccuracyField scrub in AddTrait/RemoveTrait/
        // ClearAutoGeneratedUniqueState.
        internal static readonly FieldInfo VerbBurstTicksField = typeof(Verb)
            .GetField("cachedTicksBetweenBurstShots", BindingFlags.NonPublic | BindingFlags.Instance);

        internal static readonly FieldInfo VerbBurstCountField = typeof(Verb)
            .GetField("cachedBurstShotCount", BindingFlags.NonPublic | BindingFlags.Instance);

        /// <summary>
        /// Verifies that every cached CompUniqueWeapon FieldInfo resolved.
        /// Should be called during StaticConstructorOnStartup so a RimWorld
        /// API rename surfaces as a startup error rather than a silent no-op
        /// on every later SetName/SetColor/AddTrait/RemoveTrait. Pure
        /// diagnostic — no state is built here; the FieldInfos are resolved
        /// at class-load time by the field initializers above.
        /// </summary>
        public static void VerifyReflection()
        {
            if (CompNameField == null)
                Log.Error("[Persona Weapons Unbound] CompUniqueWeapon.name field not found via reflection; "
                    + "weapon renaming will silently no-op. RimWorld API may have changed.");
            if (CompColorField == null)
                Log.Error("[Persona Weapons Unbound] CompUniqueWeapon.color field not found via reflection; "
                    + "weapon color changes will silently no-op. RimWorld API may have changed.");
            if (IgnoreAccuracyField == null)
                Log.Error("[Persona Weapons Unbound] CompUniqueWeapon.ignoreAccuracyMaluses field not found via reflection; "
                    + "accuracy-malus cache won't be invalidated after trait changes. RimWorld API may have changed.");
            if (VerbBurstTicksField == null)
                Log.Error("[Persona Weapons Unbound] Verb.cachedTicksBetweenBurstShots field not found via reflection; "
                    + "burst-speed trait changes won't take effect until save reload. RimWorld API may have changed.");
            if (VerbBurstCountField == null)
                Log.Error("[Persona Weapons Unbound] Verb.cachedBurstShotCount field not found via reflection; "
                    + "burst-count trait changes won't take effect until save reload. RimWorld API may have changed.");
        }

        /// <summary>
        /// Clears the per-Verb lazy caches that fold burstShotSpeedMultiplier
        /// and burstShotCountMultiplier from the weapon's trait list. Vanilla
        /// populates these on first access and never invalidates them — and
        /// they aren't Scribed, so the only thing that resets them is a save
        /// reload (private fields default back to null on the freshly-loaded
        /// Verb instance). Without this scrub, adding or removing a burst-
        /// affecting trait leaves the weapon's burst behavior frozen at the
        /// pre-change value until the player reloads.
        ///
        /// Verb instances live on the weapon's own CompEquippable.VerbTracker,
        /// not the equipping pawn, so the unequip/re-equip cycle our acquire
        /// and recovery phases drive doesn't help — the same instances persist
        /// across it, and Verb.Reset() (which Notify_PickedUp triggers) only
        /// touches per-shot state, not the burst caches.
        ///
        /// Safe on non-unique weapons (CompEquippable absent → no-op) and on
        /// weapons whose Verbs haven't been accessed yet (fields already null).
        /// </summary>
        internal static void InvalidateVerbBurstCaches(Thing weapon)
        {
            if (VerbBurstTicksField == null && VerbBurstCountField == null)
                return;
            CompEquippable comp = (weapon as ThingWithComps)?.GetComp<CompEquippable>();
            if (comp == null)
                return;
            List<Verb> verbs = comp.AllVerbs;
            if (verbs == null)
                return;
            for (int i = 0; i < verbs.Count; i++)
            {
                Verb verb = verbs[i];
                if (verb == null)
                    continue;
                VerbBurstTicksField?.SetValue(verb, null);
                VerbBurstCountField?.SetValue(verb, null);
            }
        }

        public static void AddTrait(Thing weapon, WeaponTraitDef trait)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp == null)
            {
                Log.Error("[Persona Weapons Unbound] AddTrait: weapon has no CompUniqueWeapon.");
                return;
            }

            comp.AddTrait(trait);

            // Mirror RemoveTrait: invalidate the cached ignoreAccuracyMaluses so a
            // newly-added accuracy-malus-immunity trait actually takes effect on the
            // next shot. Vanilla Setup() never resets this cache, so without this
            // the weapon's accuracy behaviour reflects the trait list at first read
            // until the comp is recreated (def conversion or save/load).
            if (IgnoreAccuracyField != null)
                IgnoreAccuracyField.SetValue(comp, null);

            // Invalidate Verb burst caches so burstShotSpeedMultiplier /
            // burstShotCountMultiplier on the new trait actually affect the
            // weapon's next shot, not just post-reload shots.
            InvalidateVerbBurstCaches(weapon);
        }

        public static void RemoveTrait(Thing weapon, WeaponTraitDef trait)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp == null)
            {
                Log.Error("[Persona Weapons Unbound] RemoveTrait: weapon has no CompUniqueWeapon.");
                return;
            }

            comp.TraitsListForReading.Remove(trait);

            // Invalidate the cached ignoreAccuracyMaluses so it recalculates on next access
            if (IgnoreAccuracyField != null)
                IgnoreAccuracyField.SetValue(comp, null);

            // Mirror AddTrait: clear Verb burst caches so removing a
            // burstShot{Speed,Count}Multiplier trait restores baseline burst
            // behavior on the next shot rather than waiting for a save reload.
            InvalidateVerbBurstCaches(weapon);
        }

        /// <summary>
        /// Scrubs the random state left behind by <c>CompUniqueWeapon.PostPostMake</c>
        /// on a freshly minted unique weapon: the auto-rolled trait list, the
        /// generated name and color, and the lazy <c>ignoreAccuracyMaluses</c> cache.
        /// Called by <see cref="WeaponDefConversion"/> right after
        /// <c>ThingMaker.MakeThing</c> on a unique-weapon def so the customization
        /// pipeline starts from a clean slate.
        ///
        /// No-op on non-unique target defs (no CompUniqueWeapon).
        /// </summary>
        internal static void ClearAutoGeneratedUniqueState(Thing weapon)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp == null)
                return;

            comp.TraitsListForReading.Clear();
            CompNameField?.SetValue(comp, null);
            CompColorField?.SetValue(comp, null);
            IgnoreAccuracyField?.SetValue(comp, null);
            InvalidateVerbBurstCaches(weapon);
        }

        public static void SetName(Thing weapon, string name)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp != null && CompNameField != null)
                CompNameField.SetValue(comp, name);

            // Keep CompArt.Title in sync for inspection dialogs
            CompArt artComp = weapon.TryGetComp<CompArt>();
            if (artComp != null && !string.IsNullOrEmpty(name))
                artComp.Title = name;
        }

        public static void SetColor(Thing weapon, ColorDef color)
        {
            CompUniqueWeapon comp = weapon.TryGetComp<CompUniqueWeapon>();
            if (comp != null && CompColorField != null)
            {
                CompColorField.SetValue(comp, color);
                weapon.Notify_ColorChanged();
            }
        }

        /// <summary>
        /// Spawns resources near a position (e.g. the workbench).
        /// Used to refund resources when removing traits.
        /// </summary>
        public static void SpawnResourcesNear(
            Map map, IntVec3 center, List<ThingDefCountClass> resources)
        {
            if (resources == null || resources.Count == 0)
                return;

            foreach (ThingDefCountClass resource in resources)
            {
                if (resource.count <= 0)
                    continue;

                Thing thing = ThingMaker.MakeThing(resource.thingDef);
                thing.stackCount = resource.count;
                GenPlace.TryPlaceThing(thing, center, map, ThingPlaceMode.Near);
            }
        }

    }
}
